version: '3.8'
name: base-test-project
services:
  api:
    container_name: api
    env_file: .env
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    env_file: .env
    image: mongo:7.0.0-rc8-jammy
    restart: always
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
